labels_to_circle_params:
  ci/binaries:
    parameter: run_binary_tests
    default_true_on:
      branches:
        - nightly
        - ci-all/.*
        - release/.*
      tags:
        - v[0-9]+(\.[0-9]+)*-rc[0-9]+
